name: CI (Build + Test)

on:
  pull_request:
    branches: [ "master", "daaboulex" ]
  push:
    branches: [ "master", "daaboulex" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libglfw3-dev "linux-headers-$(uname -r)"

      - name: Build driver
        run: make driver

      - name: Build GUI
        run: make GUI
        if: ${{ !cancelled() }}

      - name: Build yeetmousectl
        run: make yeetmousectl
        if: ${{ !cancelled() }}

      - name: Check yeetmousectl run
        run: tests/yeetmousectl_run.sh tools/yeetmousectl/yeetmousectl
        if: ${{ !cancelled() }}

      - name: Build tests
        run: |
          cmake -DYEETMOUSETESTS_ASAN=ON -DYEETMOUSETESTS_UBSAN=ON -DYEETMOUSETESTS_NO_SANITIZE_RECOVER=ON -S tests -B tests/build
          cmake --build tests/build
        if: ${{ !cancelled() }}

      - name: Run tests
        working-directory: tests/build
        run: ./YeetMouseTests
        if: ${{ !cancelled() }}